Portuguese Help Message
Vanilla-OS/apx pull request #27
Opened 2022-12-30 23:19 UTC by hugok79

2022-12-31 10:00 UTC, kbdharun approved these changes

2022-12-31 10:01 UTC, kbdharun commented on lang/pt/cmd_help
> +    version     Mostrar versão e sair
```suggestion
```

2022-12-31 14:10 UTC, hugok79 commented on lang/pt/cmd_help
> +    version     Mostrar versão e sair
> 

Done

2022-12-31 14:10 UTC, kbdharun commented on lang/pt/cmd_help
> +    version     Mostrar versão e sair
> > 
> 
> Done!

Thanks

2022-12-31 15:29 UTC, hugok79 commented
Latest commit: a7c47b5c3ff4f7f2a45b47cf697ed86eb61bf55a included

2023-03-11 07:17 UTC, kbdharun requested changes
Thanks for your contribution @hugok79. Sorry for the delay, finally we have a well-defined system for managing translations, if possible can you create a new/edit the current PR adding a `pt.yml` file under the locales directory? (You can copy and then rename the `en.yml` file)

Our current system unifies man pages and cmd help translations in a single place and translations.

2023-03-30 16:27 UTC, closed without merging

2023-03-30 21:26 UTC, hugok79 commented
> Thanks for your contribution @hugok79. Sorry for the delay, finally we have a well-defined system for managing translations, ~if possible can you create a new/edit the current PR adding a `pt.yml` file under the locales directory? (You can copy and then rename the `en.yml` file to your language code.)~
> 
> ~Our current system unifies man pages and cmd help translations in a single place.~
> 
> Edit: Apx translations are now available in weblate, feel free to contribute here https://hosted.weblate.org/projects/vanilla-os/apx/pt_BR/

Thanks for the info. Altough I only translate  Portuguese is https://hosted.weblate.org/projects/vanilla-os/apx/pt/ ! not Brazilian Portuguese https://hosted.weblate.org/projects/vanilla-os/apx/pt_BR/